### ISSUE TITLE
Can't read file on image build

### ISSUE THREAD

**Issue by ybaltouski** [spotify/docker-maven-plugin#138]
Issue:

Step 1 : ADD //home/bes/repo/colada.ms/LogAggregator/target/LogAggregator-1.0.0-SNAPSHOT.jar /opt/LogAggregator-1.0.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.285s
[INFO] Finished at: Mon Sep 21 17:07:50 MSK 2015
[INFO] Final Memory: 30M/387M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.2:build (default-cli) on project LogAggregator: Exception caught: /home/bes/repo/colada.ms/LogAggregator/target/LogAggregator-1.0.0-SNAPSHOT.jar: no such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.3.2:build (default-cli) on project LogAggregator: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:79)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: com.spotify.docker.client.DockerException: /home/bes/repo/colada.ms/LogAggregator/target/LogAggregator-1.0.0-SNAPSHOT.jar: no such file or directory
	at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:51)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:830)
	at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:517)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:307)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:93)
	... 22 more

but
bes@debian:~/repo/colada.ms/LogAggregator$ ls -l //home/bes/repo/colada.ms/LogAggregator/target/LogAggregator-1.0.0-SNAPSHOT.jar
-rw-r--r-- 1 bes bes 7239613 Sep 21 17:07 //home/bes/repo/colada.ms/LogAggregator/target/LogAggregator-1.0.0-SNAPSHOT.jar

**Comment by ybaltouski** [comment]
Sorry, dockerfile context missed

**Comment by bapetc** [comment]
I have the same issue. How did you solved it?

**Comment by brijchavda** [comment]
ybalt.. Can you please share the solution.. I am also facing the same ussue.
