### ISSUE TITLE
Pull image failed with docker 1.8.2

### ISSUE THREAD

**Issue by jerrykwchan** [spotify/docker-maven-plugin#139]
Hi,

When using docker 1.8.2 (API version 1.20), the following error return when trying to pull image from docker registry.  There is no problem when switch docker to 1.7.1 (API version 1.19).  Does anyone got the same problem?  Is there any suggestion how to solve this issue?

I'm using docker maven plugin 0.2.13.  The docker registry is version 2.  Pulling the images using docker pull works.

thanks,
Jerry

[INFO] Building image artifactory.sigma-systems.com/sigma_foundation/sigmaadminui:1.0.1-SNAPSHOT
Step 0 : FROM artifactory.sigma-systems.com/external/centos:6
Pulling repository artifactory.sigma-systems.com/external/centos
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.808 s
[INFO] Finished at: 2015-09-23T15:33:00-04:00
[INFO] Final Memory: 25M/264M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.13:build (default) on project sigmaadminui: Exception caught: Error: Status 400 trying to pull repository external/centos: "{\n  \"errors\" : [ {\n    \"status\" : 400,\n    \"message\" : \"Unsupported docker v1 repository request for 'sigma-docker'\"\n  } ]\n}" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.2.13:build (default) on project sigmaadminui: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:116)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:79)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.spotify.docker.client.DockerException: Error: Status 400 trying to pull repository external/centos: "{\n  \"errors\" : [ {\n    \"status\" : 400,\n    \"message\" : \"Unsupported docker v1 repository request for 'sigma-docker'\"\n  } ]\n}"
        at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:51)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:830)
        at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:471)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:277)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:114)
        ... 23 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Apache HTTPD log:
10.0.110.168 - - [23/Sep/2015:14:33:00 -0500] "GET /v2/ HTTP/1.1" 401 77 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"
10.0.110.168 - - [23/Sep/2015:14:33:00 -0500] "GET /v2/ HTTP/1.1" 401 77 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"
10.0.110.168 - - [23/Sep/2015:14:33:00 -0500] "GET /v1/repositories/external/centos/images HTTP/1.1" 400 124 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-123.el7.x86_64 os/linux arch/amd64"

**Comment by jerrykwchan** [comment]
I added the following line in my httpd config file and the issue is resloved
Header set Host "artifactory.sigma-systems.com"
