### ISSUE TITLE
Pull base image failed when building docker images

### ISSUE THREAD

**Issue by jerrykwchan** [spotify/docker-maven-plugin#142]
Hi,

When building docker image, pulling base image failed with error “Authentication is required” (See Maven build log) below.  The base image is located in a private registry behind Apache HTTPD reverse proxy that provide authentication.  From the HTTPD log, there is no username present in the HTTP GET request for pulling the base image, and the authentication failed.  I already put credentials in settings.xml and reference it from “server” element of pom.xml.  You can see the credentials in the Maven build log.

Why the credentials is not present in the HTTP GET request for pulling the base image?

HTTP log:
192.168.2.24 - - [06/Oct/2015:20:49:40 -0400] "GET /v2/ HTTP/1.1" 401 381 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
192.168.2.24 - - [06/Oct/2015:20:49:40 -0400] "GET /v2/ HTTP/1.1" 401 381 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"
192.168.2.24 - - [06/Oct/2015:20:49:40 -0400] "GET /v1/repositories/sigma_external/centos-java8/images HTTP/1.1" 401 381 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/3.10.0-229.11.1.el7.x86_64 os/linux arch/amd64"

Maven build log:
[INFO] Copying docker/Dockerfile -> /home/testfive/fw/sigma-adminui/sadminui/target/docker/Dockerfile
[INFO] Building image tsunami:443/sigma_foundation/sigmaadminui:1.0.1-SNAPSHOT
[DEBUG] Auth Config AuthConfig{username=testfive, password=56789012, email=testfive@tsunami.org, serverAddress=https://tsunami:443}
[DEBUG] Registry Config Json {"configs":{"https://tsunami:443":{"username":"testfive","email":"testfive@tsunami.org","password":"56789012","auth":"","serveraddress":"https://tsunami:443"}}}
[DEBUG] Registry Config Encoded eyJjb25maWdzIjp7Imh0dHBzOi8vdHN1bmFtaTo0NDMiOnsidXNlcm5hbWUiOiJ0ZXN0Zml2ZSIsImVtYWlsIjoidGVzdGZpdmVAdHN1bmFtaS5vcmciLCJwYXNzd29yZCI6IjU2Nzg5MDEyIiwiYXV0aCI6IiIsInNlcnZlcmFkZHJlc3MiOiJodHRwczovL3RzdW5hbWk6NDQzIn19fQ==
Step 0 : FROM tsunami:443/sigma_external/centos-java8:centos7
Pulling repository tsunami:443/sigma_external/centos-java8
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.489 s
[INFO] Finished at: 2015-10-06T20:49:40-04:00
[INFO] Final Memory: 34M/288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.4:build (default) on project sigmaadminui: Exception caught: Authentication is required. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.3.4:build (default) on project sigmaadminui: Exception caught
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:80)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: com.spotify.docker.client.DockerException: Authentication is required.
    at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:51)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:840)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:789)
    at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:514)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:308)
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:93)
    ... 23 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by adakappagari** [comment]
I am running into the same issue with version 0.4.0.

**Comment by adakappagari** [comment]
After debugging the issue, I found out the "Authentication required ..." error message shows up incorrectly when base images doesn't exist on the registry.

**Comment by trojanc** [comment]
I THINK I have the same issue?
The Dockerfile I'm building has a `FROM` that uses a private hosted registry that requires authentication. The system itself is signed in using `docker login docker.mycompany.com` and I can pull from command line
```
docker pull docker.mycompany.com/project/framework:latest
```

Building the image from command line works fine
```
docker build -t clientdocker.mycompany.com/project/myapp:latest .
```

Take note here that I have two different private docker registries that are used.
`docker.mycompany.com` is a generic registry for base images for many projects. Many projects will use images from this registry as a `FROM` within the Dockerfile.
`clientdocker.mycompany.com` is a client specific registry where a client's image gets stored into. Pushing to this registry with the maven plugin works fine (having the `serverId` and credentials setup in `~/.m2/settings.xml`)

When using the maven plugin to build the image it doesn't seem to send authentication when executing the `FROM`
The problem is to get the plugin to send authentication details to the first private repository where a base image needs to be pulled from.


Maven fails with 
```
Step 1 : FROM docker.mycompany.com/project/framework:latest
Pulling repository docker.mycompany.com/project/framework:latest
...
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build-image) on project my-project: Exception caught: unauthorized: authentication required -> [Help 1]
```

Ideally I'd like this credentials to be loaded from `~/.m2/settings.xml` like I already do with the credentials to push with.

**Comment by davidxia** [comment]
Does the latest version of the plugin load your ~/.docker/config.json credentials correctly?
