### ISSUE TITLE
Plugin does not support maven standard properties

### ISSUE THREAD

**Issue by sbanal** [spotify/docker-maven-plugin#153]
I tried a simple build with pom definition below and it fails when I use maven standard properties in image name. In example POM below (which has an issue), i have to replace
 `<imageName>${project.artifactId}</imageName>` with `<imageName>devops-test-webapp</imageName>` to make it work. It would be great if these properties are supported

Example pom with issue:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project>

	<modelVersion>4.0.0</modelVersion>
	<groupId>au.com.test.docker</groupId>
	<artifactId>devops-test-webapp</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<name>DevOps Sample WebApp</name>
	<description>Sample web application</description>

	<build>
		<plugins>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.3.5</version>	
				<configuration>
					<imageName>${project.artifactId}</imageName>
					<dockerDirectory>docker</dockerDirectory>
					<dockerImageTags>${project.version}</dockerImageTags>					
				</configuration>				
				<executions>
					<execution>
						<id>build</id>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
```

Maven build logs:
```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.3.5:build (build) on project devops-test-webapp: Exception caught: You must specify an "imageName" in your docker-maven-client's plugin configuration -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.3.5:build (build) on project devops-test-webapp: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:95)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:80)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.maven.plugin.MojoExecutionException: You must specify an "imageName" in your docker-maven-client's plugin configuration
        at com.spotify.docker.Utils.parseImageName(Utils.java:44)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:281)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:93)
        ... 22 more
```

**Comment by mattnworb** [comment]
The pom.xml above works for me (if I create a `docker` directory and add a `Dockerfile` to it).

```
INFO] --- docker-maven-plugin:0.3.5:build (build) @ devops-test-webapp ---
[INFO] Copying docker/Dockerfile -> /private/tmp/test-proj/target/docker/Dockerfile
[INFO] Copying docker/hello.txt -> /private/tmp/test-proj/target/docker/hello.txt
[INFO] Building image devops-test-webapp
```

This is with Maven 3.3.3. What version of Maven are you using?

**Comment by sbanal** [comment]
Hi Matt,

Looks like my issue. I used a wrong property name `${project.build.artifactId}`. The sample POM is not the one I used earlier. Sorry for wasting your time. It would be great if you have Docker compose support.

BTW, I created a sample project using this plugin. https://github.com/sbanal/docker-sample-project

Regards,
Stephen

**Comment by pramodsetlur** [comment]
Nothing seems to work for me.

```<plugin>
        <groupId>com.spotify</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <version>0.2.11</version>
        <configuration>
          <imageName>${project.name}:latest</imageName>
          <dockerDirectory>${project.build.directory}/docker-ready</dockerDirectory>
          <resources>
            <resource>
              <directory>${project.build.directory}</directory>
              <include>${project.build.finalName}.jar</include>
            </resource>
          </resources>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>build</goal>
            </goals>
            <configuration>
              <skipDockerBuild>${skip.docker}</skipDockerBuild>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

I get ```[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.11:build (default-cli) on project pramod-demo2-service-main: Exception caught: Request error: POST unix://localhost:80/build?t=demo2-service+-+main:latest: 500: HTTP 500 Internal Server Error -> [Help 1]```

I have tried various alternatives. I used `<dockerImageTag>${project.version}</dockerImageTag>` as well.

Any help is appreciated.

Thanks

**Comment by mattnworb** [comment]
@pramodsetlur the readme mentions how to troubleshoot errors like that: https://github.com/spotify/docker-maven-plugin#internalservererrorexception-http-500-internal-server-error
