### ISSUE TITLE
Does not work on ARM platforms (e.g. Hypriot Docker on Raspberry Pi)

### ISSUE THREAD

**Issue by bcopy** [spotify/docker-maven-plugin#233]
## Description

the JFFI dependency is not compatible with ARM architectures.
## How to reproduce
- Prepare a POM with base image hypriot:rpi-java (https://hub.docker.com/r/hypriot/rpi-java/)
- Build the image with Maven on a Raspberry Pi with the Hypriot raspbian image (http://blog.hypriot.com/downloads/)
## What do you expect

The docker build goal should work.
## What happened instead
- The build fails with a native exception in JFFI

NOTE : The Dockerfile is generated properly and you can still use docker build to assemble it.
## Software:
- docker version: 1.11.1
- docker-maven-plugin version: 0.4.5
- maven version: 3.0.5
## Full backtrace

``` text

[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.5:build (default-cli) on project pywebide: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider: ExceptionInInitializerError: Can't overwrite cause with java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: /tmp/jffi8109566181291199608.so: /tmp/jffi8109566181291199608.so: cannot open shared object file: No such file or directory
[ERROR] at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[ERROR] at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
[ERROR] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
[ERROR] at java.lang.Runtime.load0(Runtime.java:809)
[ERROR] at java.lang.System.load(System.java:1086)
[ERROR] at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:361)
[ERROR] at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:254)
[ERROR] at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:348)
[ERROR] at com.kenai.jffi.Init.load(Init.java:68)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ERROR] at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ERROR] at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ERROR] at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ERROR] at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ERROR] at com.kenai.jffi.Type.size(Type.java:138)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
[ERROR] at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
[ERROR] at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
[ERROR] at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ERROR] at jnr.ffi.LibraryLoader.create(LibraryLoader.java:70)
[ERROR] at jnr.unixsocket.Native.<clinit>(Native.java:72)
[ERROR] at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:68)
[ERROR] at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:49)
[ERROR] at com.spotify.docker.client.ApacheUnixSocket.<init>(ApacheUnixSocket.java:56)
[ERROR] at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:63)
[ERROR] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
[ERROR] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[ERROR] at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[ERROR] at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[ERROR] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[ERROR] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
[ERROR] at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[ERROR] at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] at java.lang.Thread.run(Thread.java:745)
[ERROR] java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/libjffi-1.2.so
[ERROR] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[ERROR] at java.lang.Runtime.load0(Runtime.java:809)
[ERROR] at java.lang.System.load(System.java:1086)
[ERROR] at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:316)
[ERROR] at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:249)
[ERROR] at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:348)
[ERROR] at com.kenai.jffi.Init.load(Init.java:68)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ERROR] at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ERROR] at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ERROR] at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ERROR] at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ERROR] at com.kenai.jffi.Type.size(Type.java:138)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
[ERROR] at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
[ERROR] at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
[ERROR] at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ERROR] at jnr.ffi.LibraryLoader.create(LibraryLoader.java:70)
[ERROR] at jnr.unixsocket.Native.<clinit>(Native.java:72)
[ERROR] at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:68)
[ERROR] at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:49)
[ERROR] at com.spotify.docker.client.ApacheUnixSocket.<init>(ApacheUnixSocket.java:56)
[ERROR] at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:63)
[ERROR] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
[ERROR] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[ERROR] at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[ERROR] at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[ERROR] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[ERROR] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
[ERROR] at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[ERROR] at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] at java.lang.Thread.run(Thread.java:745)
[ERROR] java.lang.UnsatisfiedLinkError: Can't load library: /lib/libjffi-1.2.so
[ERROR] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[ERROR] at java.lang.Runtime.load0(Runtime.java:809)
[ERROR] at java.lang.System.load(System.java:1086)
[ERROR] at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:316)
[ERROR] at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:249)
[ERROR] at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:348)
[ERROR] at com.kenai.jffi.Init.load(Init.java:68)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ERROR] at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ERROR] at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ERROR] at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ERROR] at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ERROR] at com.kenai.jffi.Type.size(Type.java:138)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
[ERROR] at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
[ERROR] at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
[ERROR] at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ERROR] at jnr.ffi.LibraryLoader.create(LibraryLoader.java:70)
[ERROR] at jnr.unixsocket.Native.<clinit>(Native.java:72)
[ERROR] at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:68)
[ERROR] at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:49)
[ERROR] at com.spotify.docker.client.ApacheUnixSocket.<init>(ApacheUnixSocket.java:56)
[ERROR] at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:63)
[ERROR] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
[ERROR] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[ERROR] at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[ERROR] at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[ERROR] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[ERROR] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
[ERROR] at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[ERROR] at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] at java.lang.Thread.run(Thread.java:745)
[ERROR] java.lang.UnsatisfiedLinkError: Can't load library: /usr/java/packages/lib/arm/libjffi-1.2.so
[ERROR] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
[ERROR] at java.lang.Runtime.load0(Runtime.java:809)
[ERROR] at java.lang.System.load(System.java:1086)
[ERROR] at com.kenai.jffi.internal.StubLoader.loadFromBootPath(StubLoader.java:316)
[ERROR] at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:249)
[ERROR] at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:434)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:348)
[ERROR] at com.kenai.jffi.Init.load(Init.java:68)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ERROR] at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ERROR] at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ERROR] at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ERROR] at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ERROR] at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ERROR] at com.kenai.jffi.Type.size(Type.java:138)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
[ERROR] at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
[ERROR] at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
[ERROR] at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[ERROR] at java.lang.Class.newInstance(Class.java:442)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
[ERROR] at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
[ERROR] at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ERROR] at jnr.ffi.LibraryLoader.create(LibraryLoader.java:70)
[ERROR] at jnr.unixsocket.Native.<clinit>(Native.java:72)
[ERROR] at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:68)
[ERROR] at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:49)
[ERROR] at com.spotify.docker.client.ApacheUnixSocket.<init>(ApacheUnixSocket.java:56)
[ERROR] at com.spotify.docker.client.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:63)
[ERROR] at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
[ERROR] at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
[ERROR] at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[ERROR] at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
[ERROR] at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
[ERROR] at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[ERROR] at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
[ERROR] at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
[ERROR] at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
[ERROR] at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
[ERROR] at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
[ERROR] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
[ERROR] at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
[ERROR] at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
[ERROR] at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
[ERROR] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR] at java.lang.Thread.run(Thread.java:745)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by bcopy** [comment]
Workaround : 

Rebuild JFFI for ARM Linux from source :
```
sudo apt-get install build-essential
git clone https://github.com/jnr/jffi.git
cd jffi
ant jar
```
 and 
```
cd build/jni
sudo cp libjffi-1.2.so /usr/lib
```

**Comment by carljmosca** [comment]
This also appears to be a potential issue on RHEL 7.

**Comment by davidxia** [comment]
@bcopy Does the latest version which contains https://github.com/spotify/docker-maven-plugin/pull/379 work?

**Comment by davidxia** [comment]
Closing for now. Please comment here if the latest version doesn't work.
