### ISSUE TITLE
Not able to deploy from OSX using remote DOCKER_HOST

### ISSUE THREAD

**Issue by bilak** [spotify/docker-maven-plugin#240]
Hello,
this is my current setup of plugin:

```
<plugin>
    <groupId>com.spotify</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <version>0.4.10</version>
    <configuration>
        <registryUrl>10.0.1.70:5000/v2</registryUrl>
        <imageName>10.0.1.70:5000/v2/${project.artifactId}</imageName>
        <dockerDirectory>src/main/docker</dockerDirectory>
        <resources>
            <resource>
                <targetPath>/</targetPath>
                <directory>${project.build.directory}</directory>
                <include>${project.build.finalName}.jar</include>
            </resource>
        </resources>
    </configuration>
</plugin>
```

remote docker version is: Docker version 1.11.2, build b9f10c
maven version is: Apache Maven 3.3.3

I have remote registry on path 10.0.1.70:5000 (which is registry v2).
When I run this command `DOCKER_HOST=10.0.1.70:2375 mvn clean package docker:build -DpushImage -X -e` plugin is trying to deploy to registry v1 and this is the output:

```
[DEBUG] Configuring mojo 'com.spotify:docker-maven-plugin:0.4.9:build' with basic configurator -->
[DEBUG]   (f) buildArgs = {}
[DEBUG]   (f) buildDirectory = /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target
[DEBUG]   (f) dockerDirectory = src/main/docker
[DEBUG]   (f) env = {}
[DEBUG]   (f) exposes = []
[DEBUG]   (f) forceTags = false
[DEBUG]   (f) imageName = 10.0.1.70:5000/v2/discovery-service
[DEBUG]   (f) imageTags = []
[DEBUG]   (f) labels = []
[DEBUG]   (f) mavenProject = MavenProject: com.test:discovery-service:1.0-SNAPSHOT @ /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/pom.xml
[DEBUG]   (f) noCache = false
[DEBUG]   (f) pullOnBuild = false
[DEBUG]   (f) pushImage = true
[DEBUG]   (f) pushImageTag = false
[DEBUG]   (f) registryUrl = 10.0.1.70:5000/v2
[DEBUG]   (s) targetPath = /
[DEBUG]   (s) directory = /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target
[DEBUG]   (s) include = discovery-service.jar
[DEBUG]   (f) resources = [Resource {targetPath: /, filtering: false, FileSet {directory: /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target, PatternSet [includes: {discovery-service.jar}, excludes: {}]}}]
[DEBUG]   (f) retryPushCount = 5
[DEBUG]   (f) retryPushTimeout = 10000
[DEBUG]   (f) runs = []
[DEBUG]   (f) skipDockerBuild = false
[DEBUG]   (f) squashRunCommands = false
[DEBUG]   (f) tagInfoFile = /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target/test-classes/image_info.json
[DEBUG]   (f) useGitCommitId = false
[DEBUG]   (f) volumes = []
[DEBUG]   (f) execution = com.spotify:docker-maven-plugin:0.4.9:build {execution: default-cli}
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@66b72664
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@16aed49f
[DEBUG] -- end configuration --
[DEBUG] /Users/bilak/.docker/ca.pem, /Users/bilak/.docker/key.pem or /Users/bilak/.docker/cert.pem does not exist, not using SSL
[DEBUG] Not a git repository, cannot get commit ID. Make sure git repository is initialized.
[DEBUG] Not using any build profile
[INFO] Copying /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target/discovery-service.jar -> /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target/docker/discovery-service.jar
[INFO] Copying src/main/docker/Dockerfile -> /Users/bilak/IdeaProjects/sources/infrastructure-services-parent/discovery-service/target/docker/Dockerfile
[INFO] Building image 10.0.1.70:5000/v2/discovery-service
[DEBUG] Auth Config null
[DEBUG] Registry Config Json {"":{"serveraddress":"","password":"","auth":"","email":"","username":""}}
[DEBUG] Registry Config Encoded eyIiOnsic2VydmVyYWRkcmVzcyI6IiIsInBhc3N3b3JkIjoiIiwiYXV0aCI6IiIsImVtYWlsIjoiIiwidXNlcm5hbWUiOiIifX0=
Step 1 : FROM java:8
 ---> 264282a59a95
Step 2 : ADD discovery-service.jar app.jar
 ---> 77af5f343b15
Removing intermediate container 624864a903d1
Step 3 : RUN bash -c 'touch /app.jar'
 ---> Running in cd442b08a628
 ---> c3773cf0ed5d
Removing intermediate container cd442b08a628
Step 4 : ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=container -jar /app.jar
 ---> Running in 586f920dc8f6
 ---> 79307c97cf55
Removing intermediate container 586f920dc8f6
Successfully built 79307c97cf55
[INFO] Built 10.0.1.70:5000/v2/discovery-service
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[WARNING] Failed to push 10.0.1.70:5000/v2/discovery-service, retrying in 10 seconds (1/5).
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[WARNING] Failed to push 10.0.1.70:5000/v2/discovery-service, retrying in 10 seconds (2/5).
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[WARNING] Failed to push 10.0.1.70:5000/v2/discovery-service, retrying in 10 seconds (3/5).
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[WARNING] Failed to push 10.0.1.70:5000/v2/discovery-service, retrying in 10 seconds (4/5).
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[WARNING] Failed to push 10.0.1.70:5000/v2/discovery-service, retrying in 10 seconds (5/5).
[INFO] Pushing 10.0.1.70:5000/v2/discovery-service
The push refers to a repository [10.0.1.70:5000/v2/discovery-service]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:23 min
[INFO] Finished at: 2016-06-17T15:19:56+02:00
[INFO] Final Memory: 45M/606M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.9:build (default-cli) on project discovery-service: Exception caught: Get https:10.0.1.70:5000/v1/_ping: tls: oversized record received with length 20527 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.9:build (default-cli) on project discovery-service: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:129)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.spotify.docker.client.exceptions.DockerException: Get https:10.0.1.70:5000/v1/_ping: tls: oversized record received with length 20527
        at com.spotify.docker.client.AnsiProgressHandler.progress(AnsiProgressHandler.java:52)
        at com.spotify.docker.Utils$DigestExtractingProgressHandler.progress(Utils.java:149)
        at com.spotify.docker.client.ProgressStream.tail(ProgressStream.java:77)
        at com.spotify.docker.client.DefaultDockerClient.push(DefaultDockerClient.java:1015)
        at com.spotify.docker.Utils.pushImage(Utils.java:83)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:363)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:127)
        ... 23 more

```

Can I somehow configure plugin to deploy to registry v2? Or is here any other issue which I don't see?

Thanks

**Comment by stemlaur** [comment]
UP please

**Comment by davidxia** [comment]
@bilak Does the latest version work for you?

**Comment by bilak** [comment]
@davidxia sorry I'm not working on that project anymore.

**Comment by davidxia** [comment]
It’s OK. I’ll close and we can open if someone has the issue again.
