### ISSUE TITLE
Request error: POST unix://localhost:80/build?t=test/test-app: 500: HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by nitin-tiwari** [spotify/docker-maven-plugin#242]
## Description

Using the plugin with Docker For Mac installation, which doesn't set the DOCKER_xx environment variables. Using docker-maven-plugin with Sprint boot app.

## How to reproduce

Create a DockerFile. and run following command
`mvn clean package -X docker:build`
DockerFile contains

```
FROM maven:3.3-jdk-8
EXPOSE 8080

VOLUME /tmp

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN mvn install
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/src/app/target/test-app-0.1.0.jar"]
```

## What do you expect

Maven builds the project, create a jar, and then use the docker plugin to build an image for the Jar.

## What happened instead

`HTTP 500 Internal Server Error`

## Software:

- docker version:  

```
docker version 1.12.0-rc2, build 906eacd, experimental, 
docker-machine version 0.8.0-rc1, build fffa6c9

```
- docker-maven-plugin version: 0.4.10
- maven version: 3.3.9

## Full backtrace

```text
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project test-app: Exception caught: Request error: POST unix://localhost:80/build?t=test/test-app: 500: HTTP 500 Internal Server Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.10:build (default-cli) on project test-app: Exception caught
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:130)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/build?t=test/test-app: 500
        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1604)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1554)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1149)
        at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1111)
        at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:562)
        at com.spotify.docker.BuildMojo.execute(BuildMojo.java:347)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:128)
        ... 23 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
        at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
        at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
        at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
        at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
        at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[ERROR] 

```

**Comment by nitin-tiwari** [comment]
docker daemon log:
`time="2016-07-04T15:38:55.553034944Z" level=debug msg="Calling POST /build?t=test/test-app" 
time="2016-07-04T15:38:58.517021925Z" level=error msg="Handler for POST /build returned error: Cannot locate specified Dockerfile: Dockerfile" `

**Comment by nitin-tiwari** [comment]
there was a typo in the filename..figured out. it works now.

**Comment by cswanghan** [comment]
Error named Dockerfile to DockerFile, with the capitalized F. 
However, hope this plugin would throw this message out directly, cause it's really a pain in the ass to find this out.

**Comment by zt1983811** [comment]
@cswanghan I had the same issue but I do not know where to fix the name of the file

**Comment by jd485057** [comment]
I hit this problem and the issue was my I had to remove this entry from `.dockerignore`
```
Dockerfile
```

**Comment by rwenz3l** [comment]
Another great scenario for this: Make sure the dockerfile is in the right place. Usually, when you recieve this message and you can use docker with other projects or just by using `docker ps`, then the issue is most probably trivial and unrelated to docker itself. In my case I had the Dockerfile in the wrong directory and maven could not copy it to the target (which is not reported) and therefore docker could not find a dockerfile. So please do a `mvn clean package docker:build` and check if the Dockerfile is actually in your target directory.
