### ISSUE TITLE
Get unqualified "java.io.IOException: No such file or directory" building simple dockerfile

### ISSUE THREAD

**Issue by davidmichaelkarr** [spotify/docker-maven-plugin#260]
On a CentOS7.2 VM, I'm assembling a docker build step-by-step.  I have a simple POM and even simpler Dockerfile.  Running "mvn docker:build" fails with an unhelpful "java.io.IOException: No such file or directory".  I added "-e" for the full stacktrace, and it still doesn't give me much information.

The full stacktrace is the following:
`Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1537)
	... 29 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: No such file or directory
	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:94)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:102)
	at com.spotify.docker.client.ApacheUnixSocket.connect(ApacheUnixSocket.java:73)
	at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
`

The POM is just this:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>orderProcessingDashboard</groupId>
  <artifactId>ordersImage</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <build>
    	<plugins>
  		<plugin>
  			<groupId>com.spotify</groupId>
  			<artifactId>docker-maven-plugin</artifactId>
  			<configuration>
  				<dockerDirectory>src/docker</dockerDirectory>
  				<imageName>ordersImage</imageName>
  			</configuration>
  		</plugin>
  	</plugins>
  </build>
</project>`

And the Dockerfile just this:
`FROM tomee:8-jdk-7.0.0-webprofile`

(I did say it was simple.)

What might be wrong here?

**Comment by davidmichaelkarr** [comment]
Something that I should have obviously mentioned is that I'm behind a corporate firewall.

Also, although the above is the "full" stacktrace, the info I get in the "short" stacktrace provides another possible clue.  It shows this:
`[INFO] Building image ordersImage
Aug 10, 2016 11:29:16 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
`

**Comment by mattnworb** [comment]
The second stacktrace sounds like the issue might be that the `DOCKER_HOST` value used by default by the plugin - which I would guess is `unix:///var/run/docker.sock` - is not valid on your system. Do you know what `DOCKER_HOST` value should be used? If it is a different value, you can set it by invoking maven like `DOCKER_HOST=foo mvn test ...`

**Comment by davidmichaelkarr** [comment]
I believe this was happening because our firewall is blocking the docker.io connection.

**Comment by mattnworb** [comment]
I don't think that a firewall rule for docker.io would cause the plugin to be unable to connect to your local DOCKER_HOST, but as long as it is working for you now I will close this.
