### ISSUE TITLE
Dreaded 500 Internal Server Error following tutorial (Windows). Please help

### ISSUE THREAD

**Issue by maiakaat** [spotify/docker-maven-plugin#269]
## Description

docker-maven-plugin successfully starts task before exiting with unidentified exception 500: Internal Server Error
## How to reproduce

**1. Install Docker for Windows**

**2. Check commands can be executed successfully**

**3. Deploy and start test images from command line**

**3. Setup a project following the Spring-Boot docker tutorial here**

https://spring.io/guides/gs/spring-boot-docker/

**4. Configure POM**

_a) Customize testing with JaCoCo
b) Make empty profiles
c) Add docker:build execution in POM
d) Remove all upper case names_

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.***.services</groupId>
  <artifactId>mmboiler</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>org..***.mmboiler</name>
    <description>...</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.4.0.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>1.8</java.version>

    <docker.image.prefix>hera</docker.image.prefix>

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-batch</artifactId>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
    </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

  <build>
    <finalName>mmboiler</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.3.2</version>
        <configuration>
          <showDeprecation>true</showDeprecation>
          <encoding>${project.build.sourceEncoding}</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>${argLine} -Dfile.encoding=${project.build.sourceEncoding}</argLine>
          <forkCount>1</forkCount>
          <reuseForks>true</reuseForks>
        </configuration>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    <plugin>
      <groupId>org.jacoco</groupId>
      <artifactId>jacoco-maven-plugin</artifactId>
      <version>0.7.7.201606060606</version>
      <executions>
        <execution>
          <id>pre-unit-test</id>
          <goals>
            <goal>prepare-agent</goal>
          </goals>
        </execution>
        <execution>
          <id>post-unit-test</id>
          <phase>test</phase>
          <goals>
            <goal>report</goal>
          </goals>
        </execution>
        <execution>
          <id>pre-integration-test</id>
          <phase>pre-integration-test</phase>
          <goals>
            <goal>prepare-agent</goal>
          </goals>
          <configuration>
            <destFile>target/jacoco-it.exec</destFile>
            <propertyName>surefireArgLine</propertyName>
          </configuration>
        </execution>
        <execution>
          <id>post-integration-test</id>
          <phase>post-integration-test</phase>
          <goals>
            <goal>report</goal>
          </goals>
          <configuration>
            <dataFile>target/jacoco-it.exec</dataFile>
          </configuration>
        </execution>
      </executions>
    </plugin>
    <plugin>
      <groupId>com.spotify</groupId>
      <artifactId>docker-maven-plugin</artifactId>
      <version>0.4.11</version>
      <configuration>
        <imageName>${docker.image.prefix}/${project.artifactId}</imageName>
        <dockerDirectory>src/main/docker</dockerDirectory>
        <resources>
          <resource>
            <targetPath>/</targetPath>
            <directory>${project.build.directory}</directory>
            <include>${project.build.finalName}.jar</include>
          </resource>
        </resources>
      </configuration>
      <executions>
        <execution>
          <id>docker-package</id>
          <phase>package</phase>
          <goals>
            <goal>build</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <!-- Test with Spring Boot using in memory non-persisted database via Tomcat -->
      <id>test-local</id>

    </profile>

    <profile>
      <!-- Connect to live docker microservice on the cloud to run tests -->
      <id>test-cloud</id>

    </profile>

    <profile>
      <!-- Deploy docker microservice container to local environment -->
      <id>deploy-local</id>

    </profile>

    <profile>
      <!-- Deploy docker microservice container to cloud -->
      <id>deploy-cloud</id>

    </profile>

  </profiles>
</project>
```

**5. Create DockerFile**

```
FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD mmboiler.jar mmboiler.jar
RUN sh -c 'touch /mmboiler.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/mmboiler.jar"]
```

**6. Run Maven Build**
## What do you expect

[Describe what do you expect to happen]

Expected no errors with visible evidence that docker:build had completed successfully

[Describe the actual results]

Maven threw an unidentifiable Internal Server Error,

No logs I could find gave any indicator to the problem

Manual entry of the dockerHost with a dud IP changed the results so that an attempt to run dockerBuild didn't actually happen, so this seems to not be the problem

All files expected were in the correct locations

All images were set to simple lowercase "mmboiler" string

No JSON message could be found in any Docker locations

Service log revealed nothing bad happening
## Software:
- docker version: 1.12.0
- docker-maven-plugin version: 0.4.11
- maven version: Internal Version with Netbeans IDE 8.1, and Externally with v3.3.3

_(see info below)_

```
PS D:\Apps\DevTools\Docker\Docker> docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64


PS D:\Apps\DevTools\Docker\Docker> docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 7
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.19 GiB
Name: moby
ID: NRI5:GTBU:VUKH:ZYEX:DZ43:E5AB:K5MK:MBJA:3K75:SX53:PHSS:WTGU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
PS D:\Apps\DevTools\Docker\Docker>
```
## Full backtrace

**Maven logs**
1. Maven threw the same error from the IDE and from direct command line execution

```
[DEBUG] Configuring mojo com.spotify:docker-maven-plugin:0.4.11:build from plugin realm ClassRealm[plugin>com.spotify:docker-maven-plugin:0.4.11, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'com.spotify:docker-maven-plugin:0.4.11:build' with basic configurator -->
[DEBUG]   (f) buildArgs = {}
[DEBUG]   (f) buildDirectory = F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target
[DEBUG]   (f) dockerDirectory = src/main/docker
[DEBUG]   (f) env = {}
[DEBUG]   (f) exposes = []
[DEBUG]   (f) forceTags = false
[DEBUG]   (f) imageName = hera/mmboiler
[DEBUG]   (f) imageTags = []
[DEBUG]   (f) labels = []
[DEBUG]   (f) mavenProject = MavenProject: org.metasort.trackai.services:mmboiler:1.0.0-SNAPSHOT @ F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\pom.xml
[DEBUG]   (f) noCache = false
[DEBUG]   (f) pullOnBuild = false
[DEBUG]   (f) pushImage = false
[DEBUG]   (f) pushImageTag = false
[DEBUG]   (s) targetPath = /
[DEBUG]   (s) directory = F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target
[DEBUG]   (s) include = mmboiler.jar
[DEBUG]   (f) resources = [Resource {targetPath: /, filtering: false, FileSet {directory: F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target, PatternSet [includes: {mmboiler.jar}, excludes: {}]}}]
[DEBUG]   (f) retryPushCount = 5
[DEBUG]   (f) retryPushTimeout = 10000
[DEBUG]   (f) runs = []
[DEBUG]   (f) skipDockerBuild = false
[DEBUG]   (f) squashRunCommands = false
[DEBUG]   (f) tagInfoFile = F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target\test-classes/image_info.json
[DEBUG]   (f) useGitCommitId = false
[DEBUG]   (f) volumes = []
[DEBUG]   (f) execution = com.spotify:docker-maven-plugin:0.4.11:build {execution: docker-package}
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@25748410
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@5df778c3
[DEBUG] -- end configuration --
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[DEBUG] Not using any build profile
[INFO] Copying F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target\mmboiler.jar -> F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target\docker\mmboiler.jar
[INFO] Copying src\main\docker\DockerFile -> F:\Jodi\Repo\Local\Prj\meta\meta.music\dev\hera\services\mmboiler\target\docker\DockerFile
[INFO] Building image hera/mmboiler
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.247s
[INFO] Finished at: Sat Aug 20 21:47:38 BST 2016
[INFO] Final Memory: 31M/144M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (docker-package) on project mmboiler: Exception caught: Request error: POST http://localhost:2375/build?t=hera/mmboiler: 500: HTTP 500 Internal Server Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (docker-package) on project mmboiler: Exception caught
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:130)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST http://localhost:2375/build?t=hera/mmboiler: 500
    at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1600)
    at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1550)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1145)
    at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1107)
    at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:562)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:347)
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:128)
    ... 22 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
    at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
    at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
    at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
    at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
    at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
    at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
    at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[ERROR] 
```

**docker logs**

```
[21:26:35.863][ApiProxy       ][Info   ] Dial Hyper-V socket 41bddb48-8832-4fc6-aea3-214e9e40530d:23a432c2-537a-4291-bcb5-d62504644739
[21:26:36.834][ApiProxy       ][Info   ] proxy << POST /build?t=hera/mmboiler
[21:33:15.786][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[21:33:15.793][ApiProxy       ][Info   ] Dial Hyper-V socket 41bddb48-8832-4fc6-aea3-214e9e40530d:23a432c2-537a-4291-bcb5-d62504644739
[21:33:15.800][ApiProxy       ][Info   ] proxy << GET /v1.24/containers/json
[21:41:22.013][VpnKit         ][Debug  ] com.docker.slirp.exe: BOOTREQUEST from c0:ff:ee:c0:ff:ee
[21:41:22.022][VpnKit         ][Debug  ] com.docker.slirp.exe: BOOTREPLY to c0:ff:ee:c0:ff:ee yiddr 192.168.65.2 siddr 192.168.65.1 dns 192.168.65.1, 192.168.65.3 router 192.168.65.1 domain local
[21:41:22.028][VpnKit         ][Debug  ] com.docker.slirp.exe: lease database updated
[21:41:27.019][VpnKit         ][Debug  ] com.docker.slirp.exe: ARP responding to: who-has 192.168.65.1?
[21:47:37.349][ApiProxy       ][Info   ] proxy >> GET /version
[21:47:37.354][ApiProxy       ][Info   ] Dial Hyper-V socket 41bddb48-8832-4fc6-aea3-214e9e40530d:23a432c2-537a-4291-bcb5-d62504644739
[21:47:37.358][ApiProxy       ][Info   ] proxy << GET /version
[21:47:37.459][ApiProxy       ][Info   ] proxy >> POST /build?t=hera/mmboiler
[21:47:37.464][ApiProxy       ][Info   ] Dial Hyper-V socket 41bddb48-8832-4fc6-aea3-214e9e40530d:23a432c2-537a-4291-bcb5-d62504644739
[21:47:37.995][ApiProxy       ][Info   ] proxy << POST /build?t=hera/mmboiler
[22:11:21.118][VpnKit         ][Debug  ] com.docker.slirp.exe: BOOTREQUEST from c0:ff:ee:c0:ff:ee
[22:11:21.125][VpnKit         ][Debug  ] com.docker.slirp.exe: BOOTREPLY to c0:ff:ee:c0:ff:ee yiddr 192.168.65.2 siddr 192.168.65.1 dns 192.168.65.1, 192.168.65.3 router 192.168.65.1 domain local
[22:11:21.130][VpnKit         ][Debug  ] com.docker.slirp.exe: lease database updated
[22:11:26.120][VpnKit         ][Debug  ] com.docker.slirp.exe: ARP responding to: who-has 192.168.65.1?
```

**Comment by maiakaat** [comment]
Hi

It looks like it's not passing all the parameters to the docker host from comparing the logs, (log lines included below) but this isn't an urgent issue for me personally anymore. I understand that you are not really supporting Windows.

I'd still be willing to open up a a VNC connection to the machine via private email exchange, to give access next week at some point if you felt you'd benefit.

I've switched to using the fabric.io plugin which works with one minor change for my windows/maven configuration (adding "./maven" to the ADD first parameter)



The fabric.io log segment is as follows:

```
[14:00:18.555][ApiProxy       ][Info   ] proxy << POST /v1.18/build?t=local%2Fmmboiler&dockerfile=DockerFile&nocache=0&forcerm=1
[14:00:18.559][ApiProxy       ][Info   ] proxy >> GET /v1.18/images/local%2Fmmboiler/json
```

I also ran the docker-compose ruby tutorial to probe the docker install for problems, it completed successfully

**Comment by tobymurray-nanometrics** [comment]
I ran into a similar issue I think, and it turns the problem went away upon changing my image name. As a sanity check, have you tried changing `<imageName>${docker.image.prefix}/${project.artifactId}</imageName>` to something super simple, like `<imageName>test</imageName>`?

Not sure if it's at all related to your issue, just thought I'd mention it!

**Comment by Gmanweb** [comment]
I had the same problem on a Ubuntu Env, and by just removing the "Capitals" got rid of the 500. Thanks @tobymurray-nanometrics 100% worked.

**Comment by maiakaat** [comment]
I went through the same process, but it had no impact, I switched to a
different docker maven plugin, hence not following it up.

**Comment by Gmanweb** [comment]
Your question still help me get around the 500.
**Error:**
`Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (docker-package) on project MyProject: Exception caught: Request error: POST http://localhost:80/build?t=gman/MyProject: 500: HTTP 500 Internal Server Error -> [Help 1]`

pom.xml
**Before:**
`<imageName>gman/MyProject</imageName>`

**After:**
`<imageName>gman/myproject</imageName>`

Hope it helps others if the near future!

**Comment by HendrikStein** [comment]
I have the same HTTP 500 Internal Server Error running `mvn docker:build` on my Mac:
My environment:

**Docker Host:**
`DOCKER_HOST:unix:///var/run/docker.sock`

**Docker Version:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64


Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

```
**Maven Version:**
```
Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 17:22:22+0200)
Maven home: /Users/spoho/Development/apache-maven-3.1.1
Java version: 1.8.0_05, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.2", arch: "x86_64", family: "mac"

```
**Docker Plugin Version:**
0.4.13

**POM**
```
<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>de.jastech</groupId>
		<artifactId>joff-parent</artifactId>
		<version>0.0.1</version>
	</parent>
	<groupId>de.jastech.discovery</groupId>
	<artifactId>joff-discovery</artifactId>
	<name>j-office-discovery</name>
	<url>http://maven.apache.org</url>
	<properties>
		<docker.image.prefix>jastech</docker.image.prefix>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-eureka-server</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>${docker.plugin.version}</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<!-- <imageName>${docker.image.prefix}_${project.artifactId}</imageName>  -->
					<imageName>testimage</imageName>
					<dockerDirectory>${project.basedir}/src/main/docker</dockerDirectory>
					<resources>
						<resource>
							<directory>${project.build.directory}</directory>
							<include>${project.build.finalName}.jar</include>
						</resource>
					</resources>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

```

**Build Output**
```
mvn -e docker:build
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for de.jastech.discovery:joff-discovery:jar:0.0.1
[WARNING] 'dependencyManagement.dependencies.dependency.exclusions.exclusion.artifactId' for com.netflix.eureka:eureka-core:jar with value '*' does not match a valid id pattern. @ org.springframework.cloud:spring-cloud-netflix-dependencies:1.2.3.RELEASE, /Users/spoho/.m2/repository/org/springframework/cloud/spring-cloud-netflix-dependencies/1.2.3.RELEASE/spring-cloud-netflix-dependencies-1.2.3.RELEASE.pom, line 274, column 19
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building j-office-discovery 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.4.13:build (default-cli) @ joff-discovery ---
[INFO] Copying /Users/spoho/Documents/workspace_fridgefiller/joff-parent/joff-discovery/target/joff-discovery-0.0.1.jar -> /Users/spoho/Documents/workspace_fridgefiller/joff-parent/joff-discovery/target/docker/joff-discovery-0.0.1.jar
[INFO] No resources will be copied, no files match specified patterns
[INFO] Building image testimage
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.168s
[INFO] Finished at: Thu Jan 26 11:34:03 CET 2017
[INFO] Final Memory: 21M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default-cli) on project joff-discovery: Exception caught: Request error: POST unix://localhost:80/build?t=testimage: 500: HTTP 500 Internal Server Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default-cli) on project joff-discovery: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:141)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/build?t=testimage: 500
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1600)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1550)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1145)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1107)
	at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:571)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:355)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:139)
	... 22 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1002)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:799)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:760)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:197)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:78)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:179)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

Anny suggestions would highly be appreciated
Thx Hendrik

**Comment by mattnworb** [comment]
@HendrikStein in case you haven't seen this note in the readme: https://github.com/spotify/docker-maven-plugin#internalservererrorexception-http-500-internal-server-error

Usually this is caused by something wrong with the local docker installation, or other times some request parameter that the plugin sends to your daemon is invalid. In either case, the logs from the docker daemon (the location depends on how you run docker) should provide more info.

**Comment by cs94njw** [comment]
My error turned out to be because it couldn't find my Dockerfile.  My pom.xml must've pointed to a different directory.

**Comment by surabhshah** [comment]
For the guys following the Windows Azure tutorial and getting this error, could try copying the *Dockerfile* to *target/docker* directory and modifying the pom file's *<dockerDirectory>* to *target/docker* as below

```
...
<dockerDirectory>target/docker</dockerDirectory>
...
```

Hope it helps!
