### ISSUE TITLE
Docker Build failure 

### ISSUE THREAD

**Issue by elioth010** [spotify/docker-maven-plugin#289]
## Description

When i run `mvn docker:build `
## Version

- docker version: 1.12.3
- docker-maven-plugin version: 0.4.11
- maven version: 3.3.5

the output says 

```Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 2ca98b1366b632ee5af9d3e1f86166b76f6e3f25
    at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:139)
    at com.spotify.docker.Git.getCommitId(Git.java:96)
    at com.spotify.docker.BuildMojo.execute(BuildMojo.java:293)
    at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:128)
    ... 23 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 2ca98b1366b632ee5af9d3e1f86166b76f6e3f25
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148)
    at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:809)
    at org.eclipse.jgit.revwalk.RevWalk.parseTree(RevWalk.java:749)
    at org.eclipse.jgit.lib.IndexDiff.<init>(IndexDiff.java:287)
    at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:129)
    ... 26 more```

**Comment by davidxia** [comment]
@elioth010 Is this still an issue? How can we repro? Looks like jgit can't find a particular git commit.

**Comment by elioth010** [comment]
Just close it

**Comment by baitiandi** [comment]
i am facing this issue,could you please share your solvtion
