### ISSUE TITLE
Unparseable port number error when setting DOCKER_HOST env variable for remote Docker

### ISSUE THREAD

**Issue by Jeckyli** [spotify/docker-maven-plugin#297]
## Description

Using IntelliJ with Maven to build. Trying to use a remote Docker host by setting env variable 

`DOCKER_HOST=tcp://my.dockerhost.com:4243`

Then will receive the following error,

```
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build-image) on project mydockerapp: Exception caught: Unparseable port number: "my.dockerhost.com:4243" -> [Help 1]
```

Running on Windows without a Docker client installation, is this a requirement? 

## Software:

- docker version: 1.11
- docker-maven-plugin version: 0.4.13
- maven version: 3.0.5

## Full backtrace

```text
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.12:build (build-image) on project mydockerapp: Exception caught: Unparseable port number: "my.dockerhost.com:4243" -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mydockerapp```

**Comment by mattnworb** [comment]
Could you rerun maven with -e and post the full stacktrace?

**Comment by Jeckyli** [comment]
Sure, here it is. I'm no expert on Maven so possibly it's me not using it correctly.

First of all here is the debug info of this env setting in Maven log,

```
[DEBUG] properties used {...,env.SYSTEMROOT=C:\WINDOWS, env.DOCKER_HOST="my.dockerhost.com:4243",...}
```
Here is the stack trace,

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.456s
[INFO] Finished at: Fri Dec 23 11:24:59 PST 2016
[INFO] Final Memory: 33M/506M
[INFO] ------------------------------------------------------------------------
[ERROR] [ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build-image) on project mydockerapp: Exception caught: Unparseable port number: "my.dockerhost.com:4243" -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (build-image) on project mydockerapp: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:141)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:86)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 25 more
Caused by: java.lang.IllegalArgumentException: Unparseable port number: "my.dockerhost.com:4243"
	at com.google.common.net.HostAndPort.fromString(HostAndPort.java:198)
	at com.spotify.docker.client.DefaultDockerClient.fromEnv(DefaultDockerClient.java:1697)
	at com.spotify.docker.AbstractDockerMojo.getBuilder(AbstractDockerMojo.java:146)
	at com.spotify.docker.AbstractDockerMojo.buildDockerClient(AbstractDockerMojo.java:153)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:138)
	... 28 more

```

**Comment by Jeckyli** [comment]
OK, looks like I'm setting up the DOCKER_HOST incorrectly. I put just `my.dockerhost.com:4243` while it's supposed to be `tcp://my.dockerhost.com:4243`. Now it works. I'll close the issue. Thanks @mattnworb for the comment though it helped me to identify the problem.

However it seems to me when I use a remote Docker to build image, the process will stuck at 

```
[INFO] Building image tpaas-api
```

for very long (a couple minutes even) before actually printing out the Docker build output. Is this normal?

**Comment by mattnworb** [comment]
The client has to upload your docker context - the directory containing the files you are building - to the remote host. How big is your directory?

**Comment by Jeckyli** [comment]
Yeah, I figured that must be the reason. The folder is not too big, a few megabytes for a jar file mainly. But the connection to the server is very slow so it took long time.
