### ISSUE TITLE
shaded.org.apache.http.conn.HttpHostConnectException: Connect to 172.31.24.89:6789 [/172.31.24.89] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by Gokulk7** [spotify/docker-maven-plugin#311]
## Description
I installed jenkins 2.32.2 version and docker on Ubuntu(AWS). While configure Docker-plugin, i updated docker url as tcp://172.31.24.89:6789. This IP details i received output of ifconfig(eth0) from my machine.

I got the below mentioned error in the time of test connection. Could you please any one help to resolve this error?

* already i verified many blog, i updated proeprly DOCKER_OPTS details, done export DOCKER_HOST also. 

Error :
shaded.org.apache.http.conn.HttpHostConnectException: Connect to 172.31.24.89:6789 [/172.31.24.89] failed: Connection refused (Connection refused)
javax.ws.rs.ProcessingException: shaded.org.apache.http.conn.HttpHostConnectException: Connect to 172.31.24.89:6789 [/172.31.24.89] failed: Connection refused (Connection refused)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:420)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:316)
	at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:26)
	at com.github.dockerjava.jaxrs.VersionCmdExec.execute(VersionCmdExec.java:13)
	at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at ......

**Comment by mattnworb** [comment]
Are you sure there is a docker daemon running on `172.31.24.89:6789`? 6789 doesn't sound like a default port.

Do you get output when you run `docker -H $yourIp ps`? e.g.

```
domaster!tugboat $> docker -H 127.0.0.1:2189 ps
Cannot connect to the Docker daemon at tcp://127.0.0.1:2189. Is the docker daemon running?
master!tugboat $> docker -H /var/run/docker.sock -H ps
Please specify only one -H
master!tugboat $> docker -H /var/run/docker.sock ps
Cannot connect to the Docker daemon at tcp://localhost:2375/var/run/docker.sock. Is the docker daemon running?
master!tugboat $> ls /var/run/docker.sock
master!tugboat $> docker -H unix:///var/run/docker.sock ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

**Comment by davidxia** [comment]
Closing due to inactivity.
