### ISSUE TITLE
ProcessingException: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by mattijsf** [spotify/docker-maven-plugin#34]
Hi,

I have an issue with using this plugin after updating to the latest boot2docker version. Here are the steps to reproduce it (hopefully). The output + error is also shown below.

1. Install latest boot2docker from boot2docker.io
2. Start boot2docker
3. Setup environment by running: `$(boot2docker shellinit)`
4. Output of `env | grep -i DOCKER_` 
> DOCKER_HOST=tcp://192.168.59.103:2376
> DOCKER_TLS_VERIFY=1
> DOCKER_CERT_PATH=/Users/mattijs/.boot2docker/certs/boot2docker-vm

5. Output of `boot2docker version`
> Boot2Docker-cli version: v1.3.1
> Git commit: 57ccdb8

5. Output of `docker version`
> Client version: 1.3.1
> Client API version: 1.15
> Go version (client): go1.3.3
> Git commit (client): 4e9bbfa
> OS/Arch (client): darwin/amd64
> Server version: 1.3.1
> Server API version: 1.15
> Go version (server): go1.3.3
> Git commit (server): 4e9bbfa

I have a pom.xml sample project containing the following basic plugin configuration:
```xml
<plugin>
  <groupId>com.spotify</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <version>0.0.23</version>
  <configuration>
    <imageName>example</imageName>
    <dockerDirectory>docker</dockerDirectory>
    <resources>
       <resource>
         <targetPath>/</targetPath>
         <directory>${project.build.directory}</directory>
         <include>${project.build.finalName}.jar</include>
       </resource>
    </resources>
  </configuration>
</plugin>
```

When I execute `mvn docker:build` I get the following output / error:
```bash
bash-4.3$ mvn docker:build
[INFO] Scanning for projects...
...
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-test-project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.0.23:build (default-cli) @ docker-test-project ---
[INFO] Copying /private/tmp/docker-test-project/target/docker-test-project-0.0.1-SNAPSHOT.jar -> /private/tmp/docker-test-project/target/docker/docker-test-project-0.0.1-SNAPSHOT.jar
[INFO] Building image example
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.579 s
[INFO] Finished at: 2014-11-08T22:13:01+01:00
[INFO] Final Memory: 15M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.0.23:build (default-cli) on project docker-test-project: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
bash-4.3$ 
```

With full debug logging:
```bash
bash-4.3$ mvn docker:build -X
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /usr/local/Cellar/maven/3.2.1/libexec
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10", arch: "x86_64", family: "mac"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/local/Cellar/maven/3.2.1/libexec/conf/settings.xml
[DEBUG] Reading user settings from /Users/mattijs/.m2/settings.xml
[DEBUG] Using local repository at /Users/mattijs/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for /Users/mattijs/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.docker.test:docker-test-project:jar:0.0.1-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix docker from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix docker to com.spotify:docker-maven-plugin from POM com.docker.test:docker-test-project:jar:0.0.1-SNAPSHOT
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.docker.test:docker-test-project:jar:0.0.1-SNAPSHOT
[DEBUG] Tasks:   [docker:build]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO] 
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-test-project 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix docker from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix docker to com.spotify:docker-maven-plugin from POM com.docker.test:docker-test-project:jar:0.0.1-SNAPSHOT
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.docker.test:docker-test-project:0.0.1-SNAPSHOT
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.spotify:docker-maven-plugin:0.0.23:build (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <baseImage>java</baseImage>
  <buildDirectory>${project.build.directory}</buildDirectory>
  <cmd>${dockerCmd}</cmd>
  <defaultProfile>${dockerDefaultBuildProfile}</defaultProfile>
  <dockerDirectory>${dockerDirectory}</dockerDirectory>
  <dockerHost>${dockerHost}</dockerHost>
  <entryPoint>[&quot;java&quot;, &quot;-jar&quot;, &quot;/docker-test-project-0.0.1-SNAPSHOT.jar&quot;]</entryPoint>
  <env>${dockerEnv}</env>
  <exposes>${dockerExposes}</exposes>
  <imageName>example</imageName>
  <maintainer>${dockerMaintainer}</maintainer>
  <profile>${dockerBuildProfile}</profile>
  <pushImage default-value="false">${pushImage}</pushImage>
  <resources>
    <resource>
      <targetPath>/</targetPath>
      <directory>/private/tmp/docker-test-project/target</directory>
      <include>docker-test-project-0.0.1-SNAPSHOT.jar</include>
    </resource>${dockerResources}</resources>
  <skipDockerBuild default-value="false">${skipDockerBuild}</skipDockerBuild>
  <tagInfoFile default-value="${project.build.testOutputDirectory}/image_info.json">${tagInfoFile}</tagInfoFile>
  <useGitCommitId default-value="false">${useGitCommitId}</useGitCommitId>
  <execution default-value="${mojoExecution}"/>
  <session default-value="${session}"/>
</configuration>
[DEBUG] =======================================================================
[INFO] 
[INFO] --- docker-maven-plugin:0.0.23:build (default-cli) @ docker-test-project ---
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG] Populating class realm maven.api
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=1, ConflictMarker.nodeCount=102, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=1, ConflictIdSorter.conflictIdCount=57, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=19, ConflictResolver.conflictItemCount=97, DefaultDependencyCollector.collectTime=462, DefaultDependencyCollector.transformTime=24}
[DEBUG] com.spotify:docker-maven-plugin:jar:0.0.23:
[DEBUG]    com.spotify:docker-client:jar:2.6.4:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.6:compile
[DEBUG]       com.google.guava:guava:jar:12.0.1:compile
[DEBUG]          com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]       org.apache.commons:commons-compress:jar:1.8.1:compile
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.3.5:compile
[DEBUG]          org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[DEBUG]          commons-logging:commons-logging:jar:1.1.3:compile
[DEBUG]          commons-codec:commons-codec:jar:1.6:compile
[DEBUG]       de.gesellix:unix-socket-factory:jar:2014-09-26T18-52-33:compile
[DEBUG]          org.codehaus.groovy:groovy-all:jar:2.3.6:runtime
[DEBUG]          org.codehaus.groovy.modules.http-builder:http-builder:jar:0.7.1:runtime
[DEBUG]             net.sf.json-lib:json-lib:jar:jdk15:2.3:runtime
[DEBUG]                commons-beanutils:commons-beanutils:jar:1.8.0:runtime
[DEBUG]                commons-collections:commons-collections:jar:3.2.1:runtime
[DEBUG]                commons-lang:commons-lang:jar:2.4:runtime
[DEBUG]                net.sf.ezmorph:ezmorph:jar:1.0.6:runtime
[DEBUG]             net.sourceforge.nekohtml:nekohtml:jar:1.9.16:runtime
[DEBUG]                xerces:xercesImpl:jar:2.9.1:runtime
[DEBUG]                   xml-apis:xml-apis:jar:1.3.04:runtime
[DEBUG]             xml-resolver:xml-resolver:jar:1.2:runtime
[DEBUG]       org.bouncycastle:bcpkix-jdk15on:jar:1.51:compile
[DEBUG]          org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
[DEBUG]    com.typesafe:config:jar:1.2.0:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.2.1:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.2.1:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:0.9.0.M2:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]             javax.inject:javax.inject:jar:1:compile
[DEBUG]          org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0:compile
[DEBUG]             aopalliance:aopalliance:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M5:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.19:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.17:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.1:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:3.2.1:compile
[DEBUG]    org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0.201312181205-r:compile
[DEBUG]       com.jcraft:jsch:jar:0.1.46:compile
[DEBUG]       com.googlecode.javaewah:JavaEWAH:jar:0.5.6:compile
[DEBUG]    com.fasterxml.jackson.core:jackson-databind:jar:2.2.3:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-core:jar:2.2.3:compile
[DEBUG] Created new class realm plugin>com.spotify:docker-maven-plugin:0.0.23
[DEBUG] Importing foreign packages into class realm plugin>com.spotify:docker-maven-plugin:0.0.23
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.spotify:docker-maven-plugin:0.0.23
[DEBUG]   Included: com.spotify:docker-maven-plugin:jar:0.0.23
[DEBUG]   Included: com.spotify:docker-client:jar:2.6.4
[DEBUG]   Included: org.slf4j:slf4j-api:jar:1.7.6
[DEBUG]   Included: com.google.guava:guava:jar:12.0.1
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: org.apache.commons:commons-compress:jar:1.8.1
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.3.5
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.3.2
[DEBUG]   Included: commons-logging:commons-logging:jar:1.1.3
[DEBUG]   Included: commons-codec:commons-codec:jar:1.6
[DEBUG]   Included: de.gesellix:unix-socket-factory:jar:2014-09-26T18-52-33
[DEBUG]   Included: org.codehaus.groovy:groovy-all:jar:2.3.6
[DEBUG]   Included: org.codehaus.groovy.modules.http-builder:http-builder:jar:0.7.1
[DEBUG]   Included: net.sf.json-lib:json-lib:jar:jdk15:2.3
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.8.0
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: commons-lang:commons-lang:jar:2.4
[DEBUG]   Included: net.sf.ezmorph:ezmorph:jar:1.0.6
[DEBUG]   Included: net.sourceforge.nekohtml:nekohtml:jar:1.9.16
[DEBUG]   Included: xerces:xercesImpl:jar:2.9.1
[DEBUG]   Included: xml-apis:xml-apis:jar:1.3.04
[DEBUG]   Included: xml-resolver:xml-resolver:jar:1.2
[DEBUG]   Included: org.bouncycastle:bcpkix-jdk15on:jar:1.51
[DEBUG]   Included: org.bouncycastle:bcprov-jdk15on:jar:1.51
[DEBUG]   Included: com.typesafe:config:jar:1.2.0
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:0.9.0.M2
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: javax.inject:javax.inject:jar:1
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.0
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.0.0.M5
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.19
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.17
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0.201312181205-r
[DEBUG]   Included: com.jcraft:jsch:jar:0.1.46
[DEBUG]   Included: com.googlecode.javaewah:JavaEWAH:jar:0.5.6
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.2.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.2.3
[DEBUG]   Excluded: org.apache.maven:maven-core:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-settings-builder:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-model-builder:jar:3.2.1
[DEBUG]   Excluded: org.apache.maven:maven-aether-provider:jar:3.2.1
[DEBUG]   Excluded: org.eclipse.aether:aether-spi:jar:0.9.0.M2
[DEBUG]   Excluded: org.eclipse.aether:aether-impl:jar:0.9.0.M2
[DEBUG]   Excluded: org.eclipse.aether:aether-api:jar:0.9.0.M2
[DEBUG]   Excluded: org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.0.0.M5
[DEBUG]   Excluded: org.codehaus.plexus:plexus-classworlds:jar:2.5.1
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:3.2.1
[DEBUG] Configuring mojo com.spotify:docker-maven-plugin:0.0.23:build from plugin realm ClassRealm[plugin>com.spotify:docker-maven-plugin:0.0.23, parent: sun.misc.Launcher$AppClassLoader@77fe0d66]
[DEBUG] Configuring mojo 'com.spotify:docker-maven-plugin:0.0.23:build' with basic configurator -->
[DEBUG]   (f) baseImage = java
[DEBUG]   (f) buildDirectory = /private/tmp/docker-test-project/target
[DEBUG]   (f) entryPoint = ["java", "-jar", "/docker-test-project-0.0.1-SNAPSHOT.jar"]
[DEBUG]   (f) env = {}
[DEBUG]   (f) exposes = []
[DEBUG]   (f) imageName = example
[DEBUG]   (f) pushImage = false
[DEBUG]   (s) targetPath = /
[DEBUG]   (s) directory = /private/tmp/docker-test-project/target
[DEBUG]   (s) include = docker-test-project-0.0.1-SNAPSHOT.jar
[DEBUG]   (f) resources = [Resource {targetPath: /, filtering: false, FileSet {directory: /private/tmp/docker-test-project/target, PatternSet [includes: {docker-test-project-0.0.1-SNAPSHOT.jar}, excludes: {}]}}]
[DEBUG]   (f) skipDockerBuild = false
[DEBUG]   (f) tagInfoFile = /private/tmp/docker-test-project/target/test-classes/image_info.json
[DEBUG]   (f) useGitCommitId = false
[DEBUG]   (f) execution = com.spotify:docker-maven-plugin:0.0.23:build {execution: default-cli}
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@64e362f2
[DEBUG] -- end configuration --
[DEBUG] Not a git repository, cannot get commit ID
[DEBUG] Not using any build profile
[INFO] Copying /private/tmp/docker-test-project/target/docker-test-project-0.0.1-SNAPSHOT.jar -> /private/tmp/docker-test-project/target/docker/docker-test-project-0.0.1-SNAPSHOT.jar
[INFO] Building image example
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.560 s
[INFO] Finished at: 2014-11-08T22:22:57+01:00
[INFO] Final Memory: 18M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.0.23:build (default-cli) on project docker-test-project: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.0.23:build (default-cli) on project docker-test-project: Exception caught
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
  at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:63)
  at com.spotify.docker.BuildMojo.execute(BuildMojo.java:72)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
  ... 19 more
Caused by: com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset
  at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:801)
  at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:741)
  at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:626)
  at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:410)
  at com.spotify.docker.BuildMojo.execute(BuildMojo.java:239)
  at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:61)
  ... 22 more
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset
  at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
  at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
  at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
  at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:739)
  ... 26 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.net.SocketException: Connection reset
  at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:517)
  at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:527)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
  at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:49)
  at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
  at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:523)
  at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:169)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
  at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
  at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
  at java.net.SocketInputStream.read(SocketInputStream.java:196)
  at java.net.SocketInputStream.read(SocketInputStream.java:122)
  at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
  at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
  at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
  at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
  at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
  at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
  at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
  at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
  at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
  at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
  at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:469)
  ... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
bash-4.3$ 
...

**Comment by delfuego** [comment]
I see from #31 that HTTPS support is now added, but is that in a version of the plugin that's accessible to the public? I'm currently including v0.1.1, and it doesn't appear to work with HTTPS API access. And I'm not able to disable HTTPS access; it's a central Docker server at my org that's HTTPS-only.

**Comment by davidxia** [comment]
@mattijsf do you still need help on this or can I close?

**Comment by mattijsf** [comment]
Yes @davidxia it works perfectly now using 0.1.2. Thanks!
