### ISSUE TITLE
Unable Push

### ISSUE THREAD

**Issue by EndOfMaster** [spotify/docker-maven-plugin#366]
## Unable Push

[The originally available push, suddenly unusable]

## I don't know how to reappear

[Add steps on how to reproduce this issue]

## Software:

- docker version:
 [Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: false]
- docker-maven-plugin version: [1.0.0]
- maven version: 
[Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
Maven home: E:\apache-maven-3.5.0\bin\..
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_141\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"]

## Full backtrace

```text
[Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T03:39:06+08:00)
Maven home: E:\apache-maven-3.5.0\bin\..
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_141\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.fusesource.jansi.* < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.helpers.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Message scheme: color
[DEBUG] Message styles: debug info warning error success failure strong mojo project
[DEBUG] Reading global settings from E:\apache-maven-3.5.0\bin\..\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\wzmwz\.m2\settings.xml
[DEBUG] Reading global toolchains from E:\apache-maven-3.5.0\bin\..\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\wzmwz\.m2\toolchains.xml
[DEBUG] Using local repository at C:\Users\wzmwz\.m2\repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for C:\Users\wzmwz\.m2\repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.jifenke.lepluslive:jifenke-back:war:1.0: (none)
[DEBUG] Looking up lifecycle mappings for packaging war from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.springframework.boot:spring-boot-starter-parent:pom:1.5.8.RELEASE: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Extension realms for project org.springframework.boot:spring-boot-dependencies:pom:1.5.8.RELEASE: (none)
[DEBUG] Looking up lifecycle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.jifenke.lepluslive:jifenke-back:war:1.0
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.quartz-scheduler:quartz:jar -> duplicate declaration of version 2.2.2 @ line 371, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[WARNING] The project com.jifenke.lepluslive:jifenke-back:war:1.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should u
se the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[DEBUG] Resolving plugin prefix docker from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix docker to com.spotify:docker-maven-plugin from POM com.jifenke.lepluslive:jifenke-back:war:1.0
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.jifenke.lepluslive:jifenke-back:war:1.0
[DEBUG] Tasks:   [docker:push]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jifenke-back 1.0
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix docker from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix docker to com.spotify:docker-maven-plugin from POM com.jifenke.lepluslive:jifenke-back:war:1.0
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, genera
te-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.jifenke.lepluslive:jifenke-back:1.0
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] Repositories (dependencies): [aliyun-maven (http://maven.aliyun.com/nexus/content/groups/public, default, releases+snapshots), jifenke-bintray (https://dl.bintray.com/jifenke/maven, default, rele
ases+snapshots), releases (http://123.57.185.8:8054/nexus/content/groups/public, default, releases+snapshots), spring-milestones (http://repo.spring.io/milestone, default, releases+snapshots), central (h
ttps://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Repositories (plugins)     : [spring-milestones (http://repo.spring.io/milestone, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.spotify:docker-maven-plugin:1.0.0:push (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <dockerCertPath>${dockerCertPath}</dockerCertPath>
  <dockerHost>${dockerHost}</dockerHost>
  <imageName>registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628</imageName>
  <registryUrl>registry.cn-beijing.aliyuncs.com</registryUrl>
  <retryPushCount default-value="5">${retryPushCount}</retryPushCount>
  <retryPushTimeout default-value="10000">${retryPushTimeout}</retryPushTimeout>
  <serverId>docker-aliyun-wzm</serverId>
  <skipDocker default-value="false">${skipDocker}</skipDocker>
  <skipDockerPush default-value="false">${skipDockerPush}</skipDockerPush>
  <execution default-value="${mojoExecution}"/>
  <session default-value="${session}"/>
  <settings default-value="${settings}"/>
</configuration>
[DEBUG] =======================================================================
[INFO]
[INFO] --- docker-maven-plugin:1.0.0:push (default-cli) @ jifenke-back ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=1, ConflictMarker.nodeCount=187, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=1, ConflictIdSorter
.conflictIdCount=86, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=6, ConflictResolver.conflictItemCount=167, DefaultDependencyCollector.collectTime=584, DefaultDependencyCollector.
transformTime=10}
[DEBUG] com.spotify:docker-maven-plugin:jar:1.0.0:
[DEBUG]    com.spotify:docker-client:jar:shaded:8.7.1:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.22:compile
[DEBUG]       com.google.guava:guava:jar:18.0:compile
[DEBUG]       com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.8.8:compile
[DEBUG]          com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.8.8:compile
[DEBUG]          com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.8:compile
[DEBUG]       com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.8.8:compile
[DEBUG]       org.glassfish.jersey.core:jersey-client:jar:2.22.2:compile
[DEBUG]          javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[DEBUG]          org.glassfish.jersey.core:jersey-common:jar:2.22.2:compile
[DEBUG]             javax.annotation:javax.annotation-api:jar:1.2:compile
[DEBUG]             org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.2:compile
[DEBUG]             org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[DEBUG]          org.glassfish.hk2:hk2-api:jar:2.4.0-b34:compile
[DEBUG]             org.glassfish.hk2:hk2-utils:jar:2.4.0-b34:compile
[DEBUG]             org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34:compile
[DEBUG]          org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34:compile
[DEBUG]          org.glassfish.hk2:hk2-locator:jar:2.4.0-b34:compile
[DEBUG]             org.javassist:javassist:jar:3.18.1-GA:compile
[DEBUG]       org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.22.2:compile
[DEBUG]       org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.2:compile
[DEBUG]          org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.22.2:compile
[DEBUG]       org.apache.commons:commons-compress:jar:1.9:compile
[DEBUG]       commons-io:commons-io:jar:2.5:compile
[DEBUG]       org.apache.httpcomponents:httpclient:jar:4.5:compile
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile
[DEBUG]          commons-codec:commons-codec:jar:1.9:compile
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[DEBUG]       com.github.jnr:jnr-unixsocket:jar:0.8:compile
[DEBUG]          com.github.jnr:jnr-ffi:jar:2.0.3:compile
[DEBUG]             com.github.jnr:jffi:jar:1.2.9:compile
[DEBUG]             com.github.jnr:jffi:jar:native:1.2.9:runtime
[DEBUG]             org.ow2.asm:asm:jar:5.0.3:compile
[DEBUG]             org.ow2.asm:asm-commons:jar:5.0.3:compile
[DEBUG]             org.ow2.asm:asm-analysis:jar:5.0.3:compile
[DEBUG]             org.ow2.asm:asm-tree:jar:5.0.3:compile
[DEBUG]             org.ow2.asm:asm-util:jar:5.0.3:compile
[DEBUG]             com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[DEBUG]          com.github.jnr:jnr-constants:jar:0.8.7:compile
[DEBUG]          com.github.jnr:jnr-enxio:jar:0.9:compile
[DEBUG]          com.github.jnr:jnr-posix:jar:3.0.12:compile
[DEBUG]       commons-lang:commons-lang:jar:2.6:compile
[DEBUG]       org.bouncycastle:bcpkix-jdk15on:jar:1.52:compile
[DEBUG]          org.bouncycastle:bcprov-jdk15on:jar:1.52:compile
[DEBUG]       ch.qos.logback:logback-classic:jar:1.2.1:compile
[DEBUG]          ch.qos.logback:logback-core:jar:1.2.1:compile
[DEBUG]    com.google.auth:google-auth-library-oauth2-http:jar:0.6.0:compile
[DEBUG]       com.google.auth:google-auth-library-credentials:jar:0.6.0:compile
[DEBUG]       com.google.http-client:google-http-client:jar:1.19.0:compile
[DEBUG]          com.google.code.findbugs:jsr305:jar:1.3.9:compile
[DEBUG]       com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[DEBUG]    com.typesafe:config:jar:1.2.0:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.3:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.3:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0:compile
[DEBUG]       org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:3.3.3:compile
[DEBUG]    org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0.201312181205-r:compile
[DEBUG]       com.jcraft:jsch:jar:0.1.46:compile
[DEBUG]       com.googlecode.javaewah:JavaEWAH:jar:0.5.6:compile
[DEBUG]    com.fasterxml.jackson.core:jackson-databind:jar:2.2.3:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3:compile
[DEBUG]       com.fasterxml.jackson.core:jackson-core:jar:2.2.3:compile
[DEBUG] Created new class realm plugin>com.spotify:docker-maven-plugin:1.0.0
[DEBUG] Importing foreign packages into class realm plugin>com.spotify:docker-maven-plugin:1.0.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.spotify:docker-maven-plugin:1.0.0
[DEBUG]   Included: com.spotify:docker-maven-plugin:jar:1.0.0
[DEBUG]   Included: com.spotify:docker-client:jar:shaded:8.7.1
[DEBUG]   Included: com.google.guava:guava:jar:18.0
[DEBUG]   Included: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.8.8
[DEBUG]   Included: com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.8.8
[DEBUG]   Included: com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.8
[DEBUG]   Included: com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.8.8
[DEBUG]   Included: org.glassfish.jersey.core:jersey-client:jar:2.22.2
[DEBUG]   Included: javax.ws.rs:javax.ws.rs-api:jar:2.0.1
[DEBUG]   Included: org.glassfish.jersey.core:jersey-common:jar:2.22.2
[DEBUG]   Included: javax.annotation:javax.annotation-api:jar:1.2
[DEBUG]   Included: org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.22.2
[DEBUG]   Included: org.glassfish.hk2:osgi-resource-locator:jar:1.0.1
[DEBUG]   Included: org.glassfish.hk2:hk2-api:jar:2.4.0-b34
[DEBUG]   Included: org.glassfish.hk2:hk2-utils:jar:2.4.0-b34
[DEBUG]   Included: org.glassfish.hk2.external:aopalliance-repackaged:jar:2.4.0-b34
[DEBUG]   Included: org.glassfish.hk2.external:javax.inject:jar:2.4.0-b34
[DEBUG]   Included: org.glassfish.hk2:hk2-locator:jar:2.4.0-b34
[DEBUG]   Included: org.javassist:javassist:jar:3.18.1-GA
[DEBUG]   Included: org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.22.2
[DEBUG]   Included: org.glassfish.jersey.media:jersey-media-json-jackson:jar:2.22.2
[DEBUG]   Included: org.glassfish.jersey.ext:jersey-entity-filtering:jar:2.22.2
[DEBUG]   Included: org.apache.commons:commons-compress:jar:1.9
[DEBUG]   Included: commons-io:commons-io:jar:2.5
[DEBUG]   Included: org.apache.httpcomponents:httpclient:jar:4.5
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-codec:commons-codec:jar:1.9
[DEBUG]   Included: org.apache.httpcomponents:httpcore:jar:4.4.5
[DEBUG]   Included: com.github.jnr:jnr-unixsocket:jar:0.8
[DEBUG]   Included: com.github.jnr:jnr-ffi:jar:2.0.3
[DEBUG]   Included: com.github.jnr:jffi:jar:1.2.9
[DEBUG]   Included: com.github.jnr:jffi:jar:native:1.2.9
[DEBUG]   Included: org.ow2.asm:asm:jar:5.0.3
[DEBUG]   Included: org.ow2.asm:asm-commons:jar:5.0.3
[DEBUG]   Included: org.ow2.asm:asm-analysis:jar:5.0.3
[DEBUG]   Included: org.ow2.asm:asm-tree:jar:5.0.3
[DEBUG]   Included: org.ow2.asm:asm-util:jar:5.0.3
[DEBUG]   Included: com.github.jnr:jnr-x86asm:jar:1.0.2
[DEBUG]   Included: com.github.jnr:jnr-constants:jar:0.8.7
[DEBUG]   Included: com.github.jnr:jnr-enxio:jar:0.9
[DEBUG]   Included: com.github.jnr:jnr-posix:jar:3.0.12
[DEBUG]   Included: commons-lang:commons-lang:jar:2.6
[DEBUG]   Included: org.bouncycastle:bcpkix-jdk15on:jar:1.52
[DEBUG]   Included: org.bouncycastle:bcprov-jdk15on:jar:1.52
[DEBUG]   Included: ch.qos.logback:logback-classic:jar:1.2.1
[DEBUG]   Included: ch.qos.logback:logback-core:jar:1.2.1
[DEBUG]   Included: com.google.auth:google-auth-library-oauth2-http:jar:0.6.0
[DEBUG]   Included: com.google.auth:google-auth-library-credentials:jar:0.6.0
[DEBUG]   Included: com.google.http-client:google-http-client:jar:1.19.0
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:1.3.9
[DEBUG]   Included: com.google.http-client:google-http-client-jackson2:jar:1.19.0
[DEBUG]   Included: com.typesafe:config:jar:1.2.0
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.3
[DEBUG]   Included: org.apache.maven:maven-aether-provider:jar:3.3.3
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.20
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.eclipse.jgit:org.eclipse.jgit:jar:3.2.0.201312181205-r
[DEBUG]   Included: com.jcraft:jsch:jar:0.1.46
[DEBUG]   Included: com.googlecode.javaewah:JavaEWAH:jar:0.5.6
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.2.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.2.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.2.3
[DEBUG] Configuring mojo com.spotify:docker-maven-plugin:1.0.0:push from plugin realm ClassRealm[plugin>com.spotify:docker-maven-plugin:1.0.0, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'com.spotify:docker-maven-plugin:1.0.0:push' with basic configurator -->
[DEBUG]   (f) imageName = registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628
[DEBUG]   (f) registryUrl = registry.cn-beijing.aliyuncs.com
[DEBUG]   (f) retryPushCount = 5
[DEBUG]   (f) retryPushTimeout = 10000
[DEBUG]   (f) serverId = docker-aliyun-wzm
[DEBUG]   (f) skipDocker = false
[DEBUG]   (f) skipDockerPush = false
[DEBUG]   (f) execution = com.spotify:docker-maven-plugin:1.0.0:push {execution: default-cli}
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@7ee55e70
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@7668d560
[DEBUG] -- end configuration --
[DEBUG] C:\Users\wzmwz\.docker\ca.pem, C:\Users\wzmwz\.docker\key.pem or C:\Users\wzmwz\.docker\cert.pem does not exist, not using SSL
[DEBUG] Using configfile: C:\Users\wzmwz\.dockercfg
[DEBUG] Failed to load Google application default credentials
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must
 be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:111)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:103)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:76)
        at com.spotify.docker.AbstractDockerMojo.googleContainerRegistryAuthSupplier(AbstractDockerMojo.java:352)
        at com.spotify.docker.AbstractDockerMojo.authSupplier(AbstractDockerMojo.java:285)
        at com.spotify.docker.AbstractDockerMojo.buildDockerClient(AbstractDockerMojo.java:178)
        at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:148)
        at com.spotify.docker.PushMojo.execute(PushMojo.java:38)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Using authentication suppliers: [ConfigFileRegistryAuthSupplier, NoOpRegistryAuthSupplier]
[INFO] Pushing registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628
The push refers to a repository [registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back]
[WARNING] Failed to push registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628, retrying in 10 seconds (1/5).
[INFO] Pushing registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628
The push refers to a repository [registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back]
[WARNING] Failed to push registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:20171220081628, retrying in 10 seconds (2/5).
]
```

**Comment by mattnworb** [comment]
Without knowing what is in `C:\Users\wzmwz\.dockercfg` or what is in your pom.xml we can't really offer any suggestions. Have you seen the section of the README that covers this? https://github.com/spotify/docker-maven-plugin#using-with-private-registries

**Comment by EndOfMaster** [comment]
this is my pom about docker plugin

[<plugin>
                <groupId>com.spotify</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>1.0.0</version>
                <configuration>
                    <imageName>registry.cn-beijing.aliyuncs.com/jifenke-wzm/jifenke-back:${maven.build.timestamp}
                    </imageName>
                    <dockerDirectory>src/main/docker</dockerDirectory>
                    <resources>
                        <resource>
                            <targetPath>/</targetPath>
                            <directory>${project.build.directory}</directory>
                            <include>${project.build.finalName}.war</include>
                        </resource>
                    </resources>
                    <serverId>docker-aliyun-wzm</serverId>
                    <registryUrl>registry.cn-beijing.aliyuncs.com</registryUrl>
                </configuration>
            </plugin>
             <resource>
                <targetPath>../docker</targetPath>
                <filtering>true</filtering>
                <directory>src/main/docker</directory>
                <includes>
                    <include>**/Dockerfile</include>
                </includes>
            </resource>]

**Comment by davidxia** [comment]
Is this still an issue with the latest version?

**Comment by Resvina** [comment]
whats the fix? I'm having similar situation

**Comment by shaotongyao** [comment]
May I ask how you fixed it

**Comment by Gageonea** [comment]
Is it possible to share the fix on this issue?

**Comment by wsapiens** [comment]
I have the exact same issue with version 1.2.0 and hope to turn that off
