### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by velo** [spotify/docker-maven-plugin#61]
Hi,

I'm trying to use this plugin on my CI server and I got the following error:
````
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.2.3-contaazul-1:build (default) on project heimdall-dist: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.spotify:docker-maven-plugin:0.2.3-contaazul-1:build (default) on project heimdall-dist: Exception caught
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.MojoExecutionException: Exception caught
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:117)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:79)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 11 more
Caused by: com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1070)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1010)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:787)
	at com.spotify.docker.BuildMojo.buildImage(BuildMojo.java:456)
	at com.spotify.docker.BuildMojo.execute(BuildMojo.java:263)
	at com.spotify.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:115)
	... 14 more
Caused by: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:293)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1008)
	... 18 more
Caused by: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:517)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:527)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:293)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:49)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:45)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:523)
	at org.glassfish.jersey.client.ClientRuntime$1.run(ClientRuntime.java:169)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:320)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:201)
	... 5 more
Caused by: java.io.IOException: No such file or directory
	at jnr.unixsocket.UnixSocketChannel.doConnect(UnixSocketChannel.java:94)
	at jnr.unixsocket.UnixSocketChannel.connect(UnixSocketChannel.java:102)
	at com.spotify.docker.client.ApacheUnixSocket.connect(ApacheUnixSocket.java:71)
	at com.spotify.docker.client.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:78)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:469)
	... 20 more
````

How can I figure out which file or directory is missing?

**Comment by rohansingh** [comment]
Looks like you haven't specified a `DOCKER_HOST` so the plugin is defaulting to `unix:///var/run/docker.sock` on Linux, which doesn't exist in your case. [1]

Your options are:

1. Specify the `DOCKER_HOST` variable to be whatever your Docker endpoint actually is on your CI server.
2. Have Docker on your CI server listen on the default Unix endpoint (unix:///var/run/docker.sock).

[1]: Looks like our documentation is outdated regarding this. The docs say we'll default to `tcp://localhost:2375`, but that's only true on non-Linux systems. On Linux, we default to the Unix endpoint.

**Comment by velo** [comment]
Hrmmm, you right, there is no docker on CI, my bad.

Thanks!

**Comment by tentelemed** [comment]
Hello,
I'm getting the same error. Building my project on the same host as docker. Tried export DOCKER_HOST=tcp://localhost:2375 and export DOCKER_HOST=tcp://10.0.2.15:2375 but to no avail. 
Any other ideas ?
Cheers

**Comment by newbiesitl** [comment]
my problem was the docker was not running, starting docker solved the problem
